spring.application.name=post
spring.h2.console.enabled=true
#set fix URL
spring.datasource.url=jdbc:h2:mem:postengine
spring.jpa.defer-datasource-initialization=true

#JPA logging
#query at debug level
logging.level.org.hibernate.SQL=DEBUG

#query line down
spring.jpa.properties.hibernate.format_sql=true

#present value of parameters
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE